export const GET_LOGIN = "GET_LOGIN"
export const GET_OTP = "GET_OTP"
export const REFERRAL_VERIFICATION = "REFERRAL_VERIFICATION"
export const GET_SIGNUP = "GET_SIGNUP"

export const EMAIL_VERIFICATION_REQUEST = "EMAIL_VERIFICATION_REQUEST"
export const EMAIL_VERIFICATION = "EMAIL_VERIFICATION"